/**
 * Product registry — the single source of truth for this docs site.
 *
 * The DATA lives in products.json so that it can be read and safely edited by
 * machines (the docs-admin panel appends a JSON entry via the Git API when a
 * product is registered — it never has to rewrite JS code). This module owns
 * the BEHAVIOR generated from that data: the docs plugin instances, the navbar
 * "Products" dropdown, the homepage hub cards, the footer column, and the
 * per-product search context.
 *
 * Adding a product means adding ONE entry to products.json. Everything else
 * is generated. Before this registry those lived in three separate
 * hand-maintained places, which is how the entire API section once ended up
 * with no sidebar — it was added to the navbar and nobody updated sidebars.js.
 *
 * `status`:
 *   'live'    — has a docs folder and gets its own plugin instance + routes
 *   'planned' — listed in the UI so the roadmap is visible, but no instance is
 *               created (Docusaurus fails on an empty docs directory)
 *
 * `sidebar` is OPTIONAL for live products: when omitted, the product uses the
 * shared autogenerated sidebar (sidebars/autogen.js), so its folder structure
 * is its navigation and pages appear without any code edit. The three original
 * products keep their curated sidebar files.
 *
 * Two icon fields, because the two contexts cannot share one mechanism:
 *   navClass — a CSS-mask class from src/css/sidebar-icons.css, for the navbar
 *              and sidebar, which accept only a className
 *   icon     — a name from src/components/Icon, for React surfaces
 */
import fs from "node:fs";

const AUTOGEN_SIDEBAR = "./sidebars/autogen.js";

/** @type {Array<{
 *   id: string, label: string, blurb: string, status: 'live'|'planned',
 *   path?: string, sidebar?: string, navClass: string, icon: string,
 *   entry?: string, repo?: string
 * }>} */
export const PRODUCTS = JSON.parse(
  fs.readFileSync(new URL("./products.json", import.meta.url), "utf8")
);

/** Products that have docs, and therefore a plugin instance and routes. */
export const LIVE_PRODUCTS = PRODUCTS.filter((p) => p.status === "live");

/** One `plugin-content-docs` instance per live product. */
export const docsPlugins = () =>
  LIVE_PRODUCTS.map((p) => [
    "@docusaurus/plugin-content-docs",
    {
      id: p.id,
      path: p.path,
      routeBasePath: p.id,
      sidebarPath: p.sidebar ?? AUTOGEN_SIDEBAR,
      editUrl: "https://github.com/Razor-Infotech/hcmDoc/tree/main/",
      showLastUpdateTime: true,
      showLastUpdateAuthor: true,
    },
  ]);

/**
 * The navbar "Products" dropdown. Live products link straight into their docs;
 * planned ones point at the homepage hub, where they render as "Planned"
 * cards — visible on the roadmap without being a destination that 404s.
 */
export const navbarProductItems = () =>
  PRODUCTS.map((p) =>
    p.status === "live"
      ? { to: p.entry, label: p.label, className: p.navClass }
      : { to: "/", label: `${p.label} — soon`, className: p.navClass }
  );

/** Search is scoped per product, so a reader in /hcm does not get MS1 hits. */
export const searchContexts = () => LIVE_PRODUCTS.map((p) => p.id);
