/**
 * Shared autogenerated sidebar — the default for any product that does not
 * declare its own curated sidebar file in products.json.
 *
 * With this, a product's folder structure IS its sidebar: create
 * docs/<product>/<module>/<page>.md and it appears, no code edit. Labels and
 * ordering are controlled by _category_.json files inside the docs folders.
 */
const sidebars = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
