/**
 * Human Maximizer (the HRMS). Two lanes: guides and the endpoint reference.
 */
const sidebars = {
  hcmSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      className: "si-rocket",
      collapsible: true,
      collapsed: false,
      items: [
        "getting-started/project-setup",
        "getting-started/installation",
        "getting-started/environment-setup",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      className: "si-layers",
      collapsible: true,
      collapsed: false,
      items: ["architecture/overview"],
    },
    {
      type: "category",
      label: "Backend",
      className: "si-backend",
      collapsible: true,
      collapsed: true,
      items: [
        "backend/service-map",
        "backend/authentication",
        "backend/payroll-lifecycle",
        "backend/error-handling",
        "backend/services",
        "backend/middlewares",
        "backend/utils",
      ],
    },
    {
      type: "category",
      label: "Frontend",
      className: "si-frontend",
      collapsible: true,
      collapsed: true,
      items: [
        "frontend/overview",
        "frontend/modules",
        "frontend/contexts",
        "frontend/stores",
        "frontend/services",
        "frontend/utils",
      ],
    },
    {
      type: "category",
      label: "Modules",
      className: "si-modules",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "modules/index" },
      items: [
        {
          type: "category",
          label: "Core HR",
          className: "si-people",
          collapsed: true,
          items: [
            "modules/employee-management",
            "modules/onboarding",
            "modules/registration",
            "modules/resignation-fnf",
            "modules/company-settings",
          ],
        },
        {
          type: "category",
          label: "Time & Attendance",
          className: "si-time",
          collapsed: true,
          items: [
            "modules/attendance-leave",
            "modules/roster-management",
            "modules/geolocation",
          ],
        },
        {
          type: "category",
          label: "Payroll",
          className: "si-payroll",
          collapsed: true,
          items: ["modules/payroll"],
        },
        {
          type: "category",
          label: "Talent",
          className: "si-talent",
          collapsed: true,
          items: [
            "modules/recruitment",
            "modules/performance",
            "modules/performance-management-part1-overview",
            "modules/performance-management-part2-kpi-management",
            "modules/performance-management-part3-rating-management",
            "modules/performance-management-part4-bulk-operations",
            "modules/performance-management-part5-dashboards-analytics",
            "modules/performance-management-part6-api-reference",
            "modules/employee-engagement-detailed",
          ],
        },
        {
          type: "category",
          label: "Work Management",
          className: "si-work",
          collapsed: true,
          items: [
            "modules/task-management",
            "modules/ticket-management",
            "modules/document-center",
            "modules/asset-inventory",
          ],
        },
        {
          type: "category",
          label: "Analytics",
          className: "si-analytics",
          collapsed: true,
          items: [
            "modules/dashboard-analytics",
            "modules/productivity",
            "modules/raci-analytics",
          ],
        },
        {
          type: "category",
          label: "Platform",
          className: "si-platform",
          collapsed: true,
          items: ["modules/notifications", "modules/compliance"],
        },
      ],
    },
    {
      type: "category",
      label: "Operations",
      className: "si-ops",
      collapsible: true,
      collapsed: true,
      items: ["devops/deployment"],
    },
  ],

  hcmApiSidebar: [
    "API/index",
    {
      type: "category",
      label: "Identity & Access",
      className: "si-identity",
      collapsed: false,
      items: [
        "API/Authentication/auth-setup",
        "API/user-management/user-management",
        "API/subordinates-management/subordinates-management",
      ],
    },
    {
      type: "category",
      label: "People Operations",
      className: "si-peopleops",
      collapsed: false,
      items: [
        "API/employee-onboarding/employee-onboarding",
        "API/department-management/department-management",
        "API/designation-management/designation-management",
        "API/company-settings/company-settings",
      ],
    },
    {
      type: "category",
      label: "Time & Attendance",
      className: "si-time",
      collapsed: false,
      items: [
        "API/attendance-management/attendance-management",
        "API/leave-management/leave-management",
        "API/holiday-management/holiday-management",
      ],
    },
    {
      type: "category",
      label: "Work & Delivery",
      className: "si-delivery",
      collapsed: false,
      items: [
        "API/task-management/task-management",
        "API/tickets-management/tickets-management",
        "API/raci-management/raci-management",
      ],
    },
    {
      type: "category",
      label: "Talent",
      className: "si-talent",
      collapsed: false,
      items: [
        "API/recruitment-management/recruitment-management",
        "API/performance-management/kpi-management",
        "API/performance-management/performance-ratings-managemenet",
        "API/employee-engagement/employee-engagement",
      ],
    },
    {
      type: "category",
      label: "Compliance",
      className: "si-compliance",
      collapsed: false,
      items: ["API/posh-management/posh-management"],
    },
  ],
};

export default sidebars;
